use std::collections::HashMap;
use std::env;
use std::error::Error;

use toml::Table;

use file::File;
use issue::IssueTracker;
use location::Location;
use meta::Meta;
use rcsubstring::RcSubString;
use section::Section;

use crate::program::Program;

// Include files generated by `build.rs`
include! {concat!(env!("OUT_DIR"), "/functions.rs")}
include! {concat!(env!("OUT_DIR"), "/variables.rs")}
include! {concat!(env!("OUT_DIR"), "/globals.rs")}
include! {concat!(env!("OUT_DIR"), "/config.rs")}

mod access;
mod ast;
mod context;
mod file;
mod first_pass;
mod functions;
mod issue;
mod iterators;
mod lints;
mod located_ast;
mod location;
mod meta;
mod operators;
mod parser;
mod preprocessor;
mod program;
mod rcsubstring;
mod scopes;
mod section;
mod symbols;
mod value;
mod variables;

fn main() -> Result<(), Box<dyn Error>> {
    #[cfg(windows)]
    {
        // Enable ANSI escape codes on Windows 10
        colored::control::set_virtual_terminal(true).expect("Unable to enable virtual terminal");
    }

    let args: Vec<String> = env::args().collect();
    if args.len() != 2 {
        return Err("Usage: jsfx-lint [filepath | -]".into());
    }
    let path = &args[1];
    let entry_file = if path == "-" {
        Rc::new(File::from_stdin()?)
    } else {
        Rc::new(File::from_cli_arg(&args[1])?)
    };

    let config = get_config()?;
    let mut issue_tracker = IssueTracker::new_with_config(config);
    let program = Program::from_file(&entry_file, &mut issue_tracker)?;
    program.lint(&mut issue_tracker);
    issue_tracker.report()?;
    Ok(())
}

fn get_config() -> Result<HashMap<IssueKind, Severity>, Box<dyn Error>> {
    let mut config = get_default_config();
    let config_path = env::current_exe()?
        .parent()
        .expect("Unable to find parent directory")
        .join("config.toml");
    if config_path.exists() {
        let config_toml = std::fs::read_to_string(config_path)?;
        let config_table = config_toml.parse::<Table>()?;
        for (key, value) in config_table {
            let Some(value) = value.as_str() else {
                panic!("Value is not a string");
            };
            let Some(severity) = string_to_severity(value) else {
                panic!("Value is not a valid severity");
            };
            let Some(issue_kind) = string_to_issue_kind(&key) else {
                panic!("Key is not a valid issue kind");
            };
            config.insert(issue_kind, severity);
        }
    }
    Ok(config)
}
